import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav aria-label="fastcampus">fastcampus</nav>

      <div role="banner"></div>

      <div title="lectureList">
        <h1>강의목록</h1>
      </div>

      <footer className={styles.footer}>
        footer
      </footer>
    </div>
  )
}

export default Home
